Update ebt-deployer.yml

diff --git a/.github/workflows/ebt-deployer.yml b/.github/workflows/ebt-deployer.yml
--- a/.github/workflows/ebt-deployer.yml
+++ b/.github/workflows/ebt-deployer.yml
@@ -79,12 +79,16 @@ jobs:
           
           # Search for the string in the properties file
           if grep -q "$SEARCH_STRING" "$PROPERTIES_FILE"; then
-            echo "❌ String '$SEARCH_STRING' NOT found in $PROPERTIES_FILE."
-            echo "found=false" >> $GITHUB_ENV  # Store a failure flag
-            exit 1  # You can exit with status 1 to fail the job if the string is not found
+            echo "✅ String '$SEARCH_STRING' NOT found in $PROPERTIES_FILE."
+            echo "found=false" >> $GITHUB_ENV  # Store a failure flag            
           else           
-            echo "✅ String '$SEARCH_STRING' found in $PROPERTIES_FILE."
+            echo "❌ String '$SEARCH_STRING' found in $PROPERTIES_FILE."
             echo "found=true" >> $GITHUB_ENV  # Store a success flag for later use
+            # Print the content of the file where the string was found, with the string highlighted
+            echo "=== Contents of $FILE ==="
+            grep --color=always "$SEARCH_STRING" "$FILE"  # Highlight the string in the file content
+            echo "=========================="
+            exit 1  # You can exit with status 1 to fail the job if the string is not found
           fi
 
       - name: Setup Node.js
